package types

// AllCategories is the complete list of Product Hunt categories.
// Extracted from https://www.producthunt.com/categories (248 categories).
// Used for h/l navigation to cycle through all categories.
var AllCategories = []CategoryLink{
	newCat("3D & Animation", "3d-animation"),
	newCat("A/B testing tools", "a-b-testing"),
	newCat("Accounting software", "accounting"),
	newCat("Activity tracking", "activity-tracking"),
	newCat("Ad blockers", "ad-blockers"),
	newCat("Advertising tools", "advertising-tools"),
	newCat("Affiliate marketing", "affiliate-marketing"),
	newCat("AI Agent Automation", "ai-agent-automation"),
	newCat("AI Agents", "ai-agents"),
	newCat("AI Characters", "ai-characters"),
	newCat("AI Chatbots", "ai-chatbots"),
	newCat("AI Chief Of Staff", "ai-chief-of-staff"),
	newCat("AI Code Editors", "ai-code-editors"),
	newCat("AI Code Testing", "ai-code-testing"),
	newCat("AI Coding Agents", "ai-coding-agents"),
	newCat("AI Content Detection", "ai-content-detection"),
	newCat("AI Data Scientist", "ai-data-scientist"),
	newCat("AI Databases", "ai-databases"),
	newCat("AI Designer", "ai-designer"),
	newCat("AI Dictation Apps", "ai-dictation-apps"),
	newCat("AI Engineer", "ai-engineer"),
	newCat("AI Generative Media", "ai-generative-media"),
	newCat("AI Headshot Generators", "ai-headshot-generators"),
	newCat("AI Infrastructure Tools", "ai-infrastructure"),
	newCat("AI Metrics and Evaluation", "ai-metrics-and-evaluation"),
	newCat("AI notetakers", "ai-meeting-notetakers"),
	newCat("AI Presentation Software", "ai-presentation-software"),
	newCat("AI sales tools", "ai-sales-tools"),
	newCat("AI SDR", "ai-sdr"),
	newCat("AI Voice Agent Infrastructure", "ai-voice-agent-infrastructure"),
	newCat("AI Voice Agents", "ai-voice-agents"),
	newCat("Analytics Databases", "analytics-databases"),
	newCat("App switcher", "app-switcher"),
	newCat("Apps for kids", "apps-for-kids"),
	newCat("Authentication & identity tools", "authentication-identity"),
	newCat("Automation tools", "automation"),
	newCat("Avatar generators", "avatar-generators"),
	newCat("Background removal tools", "background-removal"),
	newCat("Blogging platforms", "blogging-platforms"),
	newCat("Books", "books"),
	newCat("Browser Automation", "browser-automation"),
	newCat("Budgeting apps", "budgeting-and-expense-tracking"),
	newCat("Business intelligence software", "business-intelligence"),
	newCat("Calendar apps", "calendars"),
	newCat("Camera apps", "camera-apps"),
	newCat("Camping apps", "camping-apps"),
	newCat("Chrome Extensions", "chrome-extensions"),
	newCat("Cloud Computing Platforms", "cloud-computing-platforms"),
	newCat("Code editors", "code-editors"),
	newCat("Code Review Tools", "code-review-tools"),
	newCat("Command line tools", "command-line-tools"),
	newCat("Community management", "community-management"),
	newCat("Compliance software", "compliance-software"),
	newCat("Content Management Systems", "cms"),
	newCat("Credit score tools", "credit-scores"),
	newCat("CRM software", "crm"),
	newCat("Crowdfunding", "crowdfunding"),
	newCat("Crypto exchanges", "crypto-exchanges"),
	newCat("Crypto tools", "crypto-tools"),
	newCat("Crypto wallets", "crypto-wallets"),
	newCat("Customer loyalty platforms", "customer-loyalty"),
	newCat("Customer support tools", "customer-support"),
	newCat("DAOs", "daos"),
	newCat("Data analysis tools", "data-analysis"),
	newCat("Data visualization tools", "data-visualization"),
	newCat("Databases and backend frameworks", "databases-and-backend"),
	newCat("Dating apps", "dating-apps"),
	newCat("Defi", "defi"),
	newCat("Design & Creative", "design-creative"),
	newCat("Design inspiration websites", "design-inspiration"),
	newCat("Design mockups", "design-mockups"),
	newCat("Design resources", "design-resources"),
	newCat("Digital whiteboards", "digital-whiteboards"),
	newCat("E-signature apps", "e-signature"),
	newCat("Ecommerce", "ecommerce"),
	newCat("Ecommerce platforms", "ecommerce-platforms"),
	newCat("Email clients", "email-clients"),
	newCat("Email marketing", "email-marketing"),
	newCat("Engineering & Development", "engineering-development"),
	newCat("Event software", "events"),
	newCat("Family", "family"),
	newCat("Family Care", "family-care"),
	newCat("Figma Plugins", "figma-plugins"),
	newCat("Figma Templates", "figma-templates"),
	newCat("File storage and sharing apps", "file-storage"),
	newCat("Finance", "finance"),
	newCat("Financial planning", "financial-planning"),
	newCat("Fitness", "fitness"),
	newCat("Flight booking apps", "flight-booking"),
	newCat("Foundation Models", "foundation-models"),
	newCat("Fundraising resources", "fundraising-resources"),
	newCat("Furniture", "furniture"),
	newCat("Games", "games"),
	newCat("GEO Tools", "geo-tools"),
	newCat("Git clients", "git-clients"),
	newCat("Graphic design tools", "graphic-design-tools"),
	newCat("Headless CMS software", "headless-cms"),
	newCat("Health & Fitness", "health-fitness"),
	newCat("Health Insurance", "health-insurance"),
	newCat("Hiking apps", "hiking-apps"),
	newCat("Hiring software", "hiring-software"),
	newCat("Hotel booking app", "hotel-booking"),
	newCat("Icon sets", "icon-sets"),
	newCat("Influencer marketing platforms", "influencer-marketing"),
	newCat("Interface design tools", "interface-design-tools"),
	newCat("Investing", "investing"),
	newCat("Invoicing tools", "invoicing-tools"),
	newCat("Issue tracking software", "issue-tracking-software"),
	newCat("Job boards", "job-boards"),
	newCat("Keyword research tools", "keyword-research"),
	newCat("Knowledge base software", "knowledge-base"),
	newCat("Landing page builders", "landing-page-builders"),
	newCat("Language Learning", "language-learning"),
	newCat("Lead generation software", "lead-generation"),
	newCat("Legal services", "legal-services"),
	newCat("Lifestyle", "lifestyle"),
	newCat("Link in bio tools", "link-in-bio"),
	newCat("Live streaming platforms", "live-streaming"),
	newCat("LLM Developer Tools", "llm-developer-tools"),
	newCat("LLM Fine Tuning", "llm-fine-tuning"),
	newCat("LLMs", "llms"),
	newCat("Maps and GPS", "maps-and-gps"),
	newCat("Marketing & Sales", "marketing-sales"),
	newCat("Marketing automation platforms", "marketing-automation"),
	newCat("Marketplace sites", "marketplace"),
	newCat("Medical", "medical"),
	newCat("Meditation", "meditation"),
	newCat("Microblogging platforms", "microblogging"),
	newCat("Mobile editing apps", "mobile-editing"),
	newCat("Money transfer", "money-transfer"),
	newCat("Music Generation", "music-generation"),
	newCat("Neobanks", "neobanks"),
	newCat("News", "news"),
	newCat("Newsletter platforms", "newsletter-platforms"),
	newCat("NFT creation tools", "nft-creation"),
	newCat("NFT marketplaces", "nft-marketplaces"),
	newCat("No-Code AI Agent Builder", "no-code-ai-agent-builder"),
	newCat("No-Code App Builder", "no-code-app-builder"),
	newCat("No-code Platforms", "no-code-platforms"),
	newCat("No-Code Website Builder", "no-code-website-builder"),
	newCat("Note and writing apps", "notes-documents"),
	newCat("Notion Templates", "notion-templates"),
	newCat("Observability tools", "observability-tools"),
	newCat("Online banking", "online-banking"),
	newCat("Online learning", "online-learning"),
	newCat("OpenClaw", "openclaw"),
	newCat("Outdoors platforms", "outdoors"),
	newCat("Password managers", "password-managers"),
	newCat("Payment processors", "payment-processors"),
	newCat("Payroll software", "payroll"),
	newCat("PDF Editor", "pdf-editor"),
	newCat("Photo editing", "photo-editing"),
	newCat("Photo sharing", "photo-sharing"),
	newCat("Physical Products", "physical-products"),
	newCat("Platforms", "platforms"),
	newCat("Podcasting Tools", "podcasting"),
	newCat("Predictive AI", "predictive-ai"),
	newCat("Pregnancy apps", "pregnancy"),
	newCat("Presentation Software", "presentation-software"),
	newCat("Product add-ons", "product-add-ons"),
	newCat("Product demo", "product-demo"),
	newCat("Productivity", "productivity"),
	newCat("Professional networking platforms", "professional-networking"),
	newCat("Project management software", "project-management"),
	newCat("Prompt Engineering Tools", "prompt-engineering-tools"),
	newCat("Real estate", "real-estate"),
	newCat("Real-time collaboration infra", "real-time-collaboration-infra"),
	newCat("Realtime Voice AI", "realtime-voice-ai"),
	newCat("Remote workforce tools", "remote-workforce"),
	newCat("Resume tools", "resumes"),
	newCat("Retirement planning", "retirement-planning"),
	newCat("Safety and Privacy platforms", "safety-and-privacy"),
	newCat("Sales enablement", "sales-enablement"),
	newCat("Sales training", "sales-training"),
	newCat("Savings apps", "savings-apps"),
	newCat("Scheduling software", "scheduling"),
	newCat("Screenshots and screen recording apps", "screenshots-and-screen-recording"),
	newCat("Search", "search"),
	newCat("Security software", "security-software"),
	newCat("Senior care", "senior-care"),
	newCat("SEO tools", "seo-tools"),
	newCat("Shopify Apps", "shopify-apps"),
	newCat("Shopping", "shopping"),
	newCat("Short term rentals", "short-term-rentals"),
	newCat("Slack apps", "slack-apps"),
	newCat("Sleep apps", "sleep"),
	newCat("Social & Community", "social-community"),
	newCat("Social audio apps", "social-audio"),
	newCat("Social bookmarking", "social-bookmarking"),
	newCat("Social media management tools", "social-media-management"),
	newCat("Social media scheduling tools", "social-media-scheduling"),
	newCat("Social Networking", "social-networking"),
	newCat("Space design apps", "space-design"),
	newCat("Spreadsheets", "spreadsheets"),
	newCat("Standup bots", "standup-bots"),
	newCat("Startup communities", "startup-communities"),
	newCat("Startup financial planning", "startup-financial-planning"),
	newCat("Startup incorporation", "startup-incorporation"),
	newCat("Static site generators", "static-site-generators"),
	newCat("Stock photo sites", "stock-photo-sites"),
	newCat("Stock trading platforms", "stock-trading"),
	newCat("Survey and form builders", "survey-and-form-builders"),
	newCat("Tax preparation", "tax-preparation"),
	newCat("Team collaboration software", "team-collaboration"),
	newCat("Terminals", "terminals"),
	newCat("Testing and QA software", "testing-and-qa"),
	newCat("Text-to-Speech Software", "text-to-speech-software"),
	newCat("Therapy apps", "therapy-apps"),
	newCat("Time tracking apps", "time-tracking"),
	newCat("Toys", "toys"),
	newCat("Transcription", "transcription"),
	newCat("Translation", "translation"),
	newCat("Travel", "travel"),
	newCat("Travel apps", "travel-apps"),
	newCat("Travel Insurance", "travel-insurance"),
	newCat("Travel Planning", "travel-planning"),
	newCat("Treasury management platforms", "treasury-management-platforms"),
	newCat("Twitter apps", "twitter-apps"),
	newCat("UI frameworks", "ui-frameworks"),
	newCat("Unified API", "unified-api"),
	newCat("User research", "user-research"),
	newCat("Vibe Coding Tools", "vibe-coding"),
	newCat("Video and Voice calling", "video-and-voice-calling"),
	newCat("Video conferencing", "video-conferencing"),
	newCat("Video editing", "video-editing"),
	newCat("Video hosting platforms", "video-hosting"),
	newCat("Virtual events", "virtual-events"),
	newCat("Virtual office platforms", "virtual-office"),
	newCat("Voice AI Tools", "voice-ai-tools"),
	newCat("VPN client", "vpn-client"),
	newCat("Wallpapers", "wallpapers"),
	newCat("Wearables", "wearables"),
	newCat("Weather apps", "weather-apps"),
	newCat("Web browsers", "web-browsers"),
	newCat("Web hosting services", "web-hosting"),
	newCat("Web3", "web3"),
	newCat("Webcams", "webcams"),
	newCat("Website analytics", "website-analytics"),
	newCat("Website builders", "website-builders"),
	newCat("Wireframing", "wireframing"),
	newCat("Wordpress Plugins", "wordpress-plugins"),
	newCat("Wordpress themes", "wordpress-themes"),
	newCat("Workout platforms", "workout-platforms"),
	newCat("Writing assistants", "writing-assistants"),
}

func newCat(name, slug string) CategoryLink {
	return NewCategoryLink(name, slug)
}

// CategoryIndexBySlug returns the index of the category with the given slug
// in AllCategories, or -1 if not found.
func CategoryIndexBySlug(slug string) int {
	for i, c := range AllCategories {
		if c.Slug() == slug {
			return i
		}
	}
	return -1
}
